name: build

on:
  push:
    paths-ignore:
    - 'README.org'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:sid
    
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt-get -y update
        apt-get -y install automake autoconf pkg-config make
        apt-get -y install guile-3.0 guile-3.0-libs guile-3.0-dev	
    - name: Generate scripts
      run: |
        ./autogen.sh
    - name: Run configuration script
      run: |
        ./configure
    - name: Check distribution
      run: |
        make distcheck


